apiVersion: projectriff.io/v1alpha1
kind: Topic
metadata:
  name: decimals
---

apiVersion: projectriff.io/v1alpha1
kind: Topic
metadata:
  name: binaries
spec:
  partitions: 3

---

apiVersion: projectriff.io/v1alpha1
kind: Function
metadata:
  name: binary
spec:
  protocol: http
  input: decimals
  output: binaries
  container:
    image: yebyen/binary:0.0.3-snapshot
